# Generated by Django 3.2.13 on 2024-02-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
