# Generated by Django 3.2.13 on 2024-02-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_pushtoken_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectdeliverables',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_access',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_access',
            field=models.ManyToManyField(blank=True, related_name='users', to='app_backend.Role'),
        ),
    ]
