# Generated by Django 3.2.13 on 2023-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_project_projectdetails_projectreporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.TextField(default='#ffeeee'),
            preserve_default=False,
        ),
    ]
