# Generated by Django 3.2.13 on 2024-02-12 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_auto_20240207_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.TextField()),
                ('taskStatus', models.CharField(choices=[('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Blocked', 'Blocked')], default='initiation', max_length=20)),
                ('taskStatusColor', models.CharField(choices=[('green', 'Green'), ('#ecb753', 'Yellow'), ('red', 'Red')], default='green', max_length=20)),
                ('taskColor', models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#FFFFFF', 'White'), ('#000000', 'Black'), ('#808080', 'Grey'), ('#00FFFF', 'Cyan'), ('#800000', 'Maroon'), ('#008000', 'Dark Green'), ('#000080', 'Navy')], default='green', max_length=20)),
                ('taskDetails', models.TextField()),
                ('taskCompleted', models.BooleanField(default=False)),
                ('taskStartDate', models.TextField(default='01-12-2024')),
                ('taskEndDate', models.TextField(default='09-01-2024')),
                ('enabled', models.BooleanField(default=False)),
                ('taskOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcementDate', models.TextField()),
                ('announcement', models.TextField()),
                ('announcementAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcementAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
