# Generated by Django 3.2.13 on 2023-12-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_project_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='execution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='initation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='planning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='watchers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_backend.customuser'),
            preserve_default=False,
        ),
    ]
