# Generated by Django 3.2.13 on 2023-12-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_auto_20231222_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_name',
        ),
    ]
