# Generated by Django 3.2.13 on 2023-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_auto_20231222_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.TextField(default='#000'),
        ),
    ]
