# Generated by Django 3.2.13 on 2024-02-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_alter_announcement_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.TextField(max_length=500),
        ),
    ]
