# Generated by Django 3.2.13 on 2023-12-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_customuser_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='watchers',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='watchers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_details_as_watcher', to='app_backend.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='deliverableOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details_as_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
