# Generated by Django 3.2.13 on 2024-02-16 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_alter_announcement_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReOccurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('taskName', models.TextField()),
                ('timeSlot', models.CharField(choices=[('08am', '08am'), ('12pm', '12pm'), ('04pm', '04pm'), ('08pm', '08pm'), ('12am', '12am'), ('04am', '04am'), ('07pm', '07pm')], max_length=30)),
                ('dayOfWeek', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=30)),
                ('week', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
