# Generated by Django 3.2.13 on 2023-12-22 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_auto_20231222_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='watchers',
            field=models.ManyToManyField(related_name='watched_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
