# Generated by Django 3.2.13 on 2023-12-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_project_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.TextField(default='Evangelism'),
            preserve_default=False,
        ),
    ]
