# Generated by Django 3.2.13 on 2024-05-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_auto_20240220_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='reoccurance',
            name='reoccuringEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcementDate',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='taskColor',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#000000', 'Black'), ('#808080', 'Grey'), ('#00FFFF', 'Cyan'), ('#800000', 'Maroon'), ('#008000', 'Dark Green'), ('#000080', 'Navy')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectColor',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#000000', 'Black'), ('#808080', 'Grey'), ('#00FFFF', 'Cyan'), ('#800000', 'Maroon'), ('#008000', 'Dark Green'), ('#000080', 'Navy')], default='#00FF00', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdeliverables',
            name='deliverableColor',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#000000', 'Black'), ('#808080', 'Grey'), ('#00FFFF', 'Cyan'), ('#800000', 'Maroon'), ('#008000', 'Dark Green'), ('#000080', 'Navy')], default='green', max_length=20),
        ),
        migrations.RemoveField(
            model_name='reoccurance',
            name='username',
        ),
        migrations.AddField(
            model_name='reoccurance',
            name='username',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField()),
                ('eventDate', models.TextField()),
                ('eventNote', models.TextField()),
                ('eventLocation', models.TextField()),
                ('eventDescription', models.TextField()),
                ('eventReoccuring', models.BooleanField(default=False)),
                ('eventImageUrl', models.TextField(blank=True, null=True)),
                ('eventEnable', models.BooleanField(default=False)),
                ('eventFollower', models.ManyToManyField(related_name='eventFollowers', to=settings.AUTH_USER_MODEL)),
                ('eventNotification', models.ManyToManyField(related_name='eventNotifications', to=settings.AUTH_USER_MODEL)),
                ('eventSubscribers', models.ManyToManyField(to='app_backend.Role')),
                ('eventWatcher', models.ManyToManyField(related_name='eventWatchers', to=settings.AUTH_USER_MODEL)),
                ('reoccuringInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.reoccurance')),
            ],
        ),
    ]
