# Generated by Django 3.2.13 on 2024-05-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_auto_20240518_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventFollower',
            field=models.ManyToManyField(blank=True, related_name='eventFollowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventNotification',
            field=models.ManyToManyField(blank=True, related_name='eventNotifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventReoccuring',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventWatcher',
            field=models.ManyToManyField(blank=True, related_name='eventWatchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='reoccuringInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.reoccurance'),
        ),
    ]
