# Generated by Django 3.2.13 on 2023-12-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_project_projecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.TextField()),
                ('costName', models.TextField()),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.project')),
            ],
        ),
    ]
