# Generated by Django 3.2.13 on 2023-12-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_projectexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='color',
            field=models.TextField(default='blue'),
        ),
    ]
