# Generated by Django 3.2.13 on 2024-05-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_auto_20240519_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reoccuringInfo',
        ),
    ]
