# Generated by Django 3.2.13 on 2023-12-25 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_projectexpense_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
