# Generated by Django 3.2.13 on 2024-05-23 18:37

import app_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_remove_event_reoccuringinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reoccurance',
            name='reoccuringEvent',
        ),
        migrations.RemoveField(
            model_name='reoccurance',
            name='timeSlot',
        ),
        migrations.AddField(
            model_name='reoccurance',
            name='timeOfEvent',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[app_backend.models.validate_event_image_time]),
        ),
    ]
