# Generated by Django 3.2.13 on 2024-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0012_auto_20240523_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
