# Generated by Django 3.2.13 on 2023-12-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0012_project_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='deliverableStatus',
            field=models.TextField(default='Start'),
            preserve_default=False,
        ),
    ]
