# Generated by Django 3.2.13 on 2023-12-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0013_projectdetails_deliverablestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='deliverableColor',
            field=models.TextField(default='green'),
            preserve_default=False,
        ),
    ]
