# Generated by Django 3.2.13 on 2024-05-24 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0014_auto_20240524_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.event')),
            ],
        ),
    ]
