# Generated by Django 3.2.13 on 2023-12-26 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0014_projectdetails_deliverablecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='watchers',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='watchers',
            field=models.ManyToManyField(related_name='project_details_as_watcher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('noteAuthor', models.TextField()),
                ('projectDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.projectdetails')),
            ],
        ),
    ]
