# Generated by Django 3.2.13 on 2024-05-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0015_eventnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventTime',
            field=models.TextField(default='10:00'),
            preserve_default=False,
        ),
    ]
