# Generated by Django 3.2.13 on 2023-12-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0015_auto_20231226_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectNote',
            new_name='ProjectNotes',
        ),
    ]
