# Generated by Django 3.2.13 on 2023-12-26 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0016_rename_projectnote_projectnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectnotes',
            old_name='notes',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='projectnotes',
            name='noteAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
