# Generated by Django 3.2.13 on 2024-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0016_event_eventtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
