# Generated by Django 3.2.13 on 2024-05-28 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0017_auto_20240525_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='questionAnswered',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
