# Generated by Django 3.2.13 on 2023-12-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0017_auto_20231226_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectnotes',
            old_name='projectDetail',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projectnotes',
            old_name='note',
            new_name='notes',
        ),
        migrations.DeleteModel(
            name='ProjectReporting',
        ),
    ]
