# Generated by Django 3.2.13 on 2023-12-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0018_auto_20231226_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='name',
            new_name='project_details_name',
        ),
    ]
