# Generated by Django 3.2.13 on 2024-06-01 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0019_eventsurveyquestion_eventsurveyresponse_surveyviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsurveyresponse',
            name='surveyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.eventsurveyquestion'),
        ),
        migrations.AlterField(
            model_name='eventsurveyresponse',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
