# Generated by Django 3.2.13 on 2023-12-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0019_rename_name_projectdetails_project_details_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='project_details_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projectnotes',
            old_name='name',
            new_name='project_details_name',
        ),
    ]
