# Generated by Django 3.2.13 on 2023-12-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0020_auto_20231226_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='deliverableStat',
            field=models.TextField(default='Completed'),
            preserve_default=False,
        ),
    ]
