# Generated by Django 3.2.13 on 2024-06-01 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0020_auto_20240601_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyviewed',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
