# Generated by Django 3.2.13 on 2023-12-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0021_projectdetails_deliverablestat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='deliverableStat',
        ),
    ]
