# Generated by Django 3.2.13 on 2023-12-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0022_remove_projectdetails_deliverablestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='deliverableCompletion',
            field=models.TextField(default='Done'),
            preserve_default=False,
        ),
    ]
