# Generated by Django 3.2.13 on 2023-12-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0023_projectdetails_deliverablecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_access',
            field=models.TextField(default='stakeholder'),
            preserve_default=False,
        ),
    ]
