# Generated by Django 3.2.13 on 2023-12-28 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0024_customuser_profile_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectStakeholders',
            field=models.ManyToManyField(related_name='project_stakeholders', to=settings.AUTH_USER_MODEL),
        ),
    ]
