# Generated by Django 3.2.13 on 2023-12-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0025_project_projectstakeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnotes',
            name='timeStamp',
            field=models.TextField(default='12-29-2023 01:14:11'),
            preserve_default=False,
        ),
    ]
