# Generated by Django 3.2.13 on 2024-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0026_projectnotes_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='deliverableStatus',
            field=models.CharField(choices=[('Risk', 'Risk'), ('Blocked', 'Blocked'), ('Warning', 'Warning'), ('Pending Response', 'Pending Response'), ('In Progress', 'In Progress'), ('Not yet started', 'Not yet started')], default='Not yet started', max_length=50),
        ),
    ]
