# Generated by Django 4.2.9 on 2024-01-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0027_alter_projectdetails_deliverablestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='initation',
            new_name='initiation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='watchers',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='watchers',
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.projecttype'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='deliverableStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.projectstatus'),
        ),
    ]
