# Generated by Django 4.2.9 on 2024-01-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0028_projectstatus_projecttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='project',
            name='initiation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='project',
            name='review',
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('initiation', 'Initiation'), ('planning', 'Planning'), ('execution', 'Execution'), ('live', 'Live'), ('completed', 'Completed'), ('review', 'Review')], default='initiation', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='dueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='flag',
            field=models.CharField(choices=[('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(),
        ),
    ]
