# Generated by Django 4.2.9 on 2024-01-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0030_alter_project_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flag',
            field=models.CharField(choices=[('#7CFC00', '#7CFC00'), ('Yellow', '#E4D00A'), ('Red', '##C70039')], default='green', max_length=20),
        ),
    ]
