# Generated by Django 4.2.9 on 2024-01-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0031_alter_project_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectnotes',
            old_name='project_details_name',
            new_name='project_deliverable_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='flag',
            field=models.CharField(choices=[('Green', '#7CFC00'), ('Yellow', '#E4D00A'), ('Red', '#C70039')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='deliverableColor',
            field=models.CharField(choices=[('Green', '#7CFC00'), ('Yellow', '#E4D00A'), ('Red', '#C70039')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='deliverableCompletion',
            field=models.BooleanField(default=0),
        ),
    ]
