# Generated by Django 4.2.9 on 2024-01-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0033_alter_project_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flag',
            field=models.CharField(choices=[('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='green', max_length=20),
        ),
    ]
