# Generated by Django 4.2.9 on 2024-01-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0034_alter_project_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(),
        ),
    ]
