# Generated by Django 4.2.9 on 2024-01-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0035_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(choices=[('Relationship', 'Relationship'), ('Evangelism', 'Evangelism'), ('Discipleship', 'Discipleship')], max_length=30),
        ),
    ]
