# Generated by Django 4.2.9 on 2024-01-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0036_alter_projecttype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDetails',
            new_name='ProjectDeliverables',
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.TextField(default='blue'),
        ),
    ]
