# Generated by Django 4.2.9 on 2024-01-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0037_rename_projectdetails_projectdeliverables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeliverables',
            name='deliverableCompletion',
            field=models.BooleanField(default=1),
        ),
    ]
