# Generated by Django 4.2.9 on 2024-01-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0038_alter_projectdeliverables_deliverablecompletion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectStatus',
            new_name='DeliverableStatus',
        ),
    ]
