# Generated by Django 4.2.9 on 2024-01-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0039_rename_projectstatus_deliverablestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverablestatus',
            name='name',
            field=models.CharField(choices=[('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Blocked', 'Blocked')], default='On Track', max_length=50),
        ),
    ]
