# Generated by Django 4.2.9 on 2024-01-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0042_alter_project_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flag',
            field=models.CharField(choices=[('green', 'Green'), ('#ecb753', 'Yellow'), ('red', 'Red')], default='green', max_length=20),
        ),
    ]
