# Generated by Django 4.2.9 on 2024-01-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0043_alter_project_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dueDate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.TextField(),
        ),
    ]
