# Generated by Django 4.2.9 on 2024-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0044_alter_project_duedate_alter_project_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdeliverables',
            old_name='deliverableCompletion',
            new_name='deliverableCompleted',
        ),
        migrations.RenameField(
            model_name='projectdeliverables',
            old_name='name',
            new_name='projectName',
        ),
        migrations.AlterField(
            model_name='projectdeliverables',
            name='deliverableStatus',
            field=models.CharField(choices=[('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Blocked', 'Blocked')], default='initiation', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeliverableStatus',
        ),
    ]
