# Generated by Django 4.2.9 on 2024-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0047_alter_projectdeliverables_deliverablecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeliverables',
            name='deliverableStatusColor',
            field=models.CharField(choices=[('green', 'Green'), ('#ecb753', 'Yellow'), ('red', 'Red')], default='initiation', max_length=20),
        ),
    ]
