# Generated by Django 4.2.9 on 2024-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0048_projectdeliverables_deliverablestatuscolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeliverables',
            name='deliverableCompleted',
            field=models.BooleanField(default=0),
        ),
    ]
