# Generated by Django 4.2.9 on 2024-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0050_remove_project_color_project_projectcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectColor',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#FFFFFF', 'White'), ('#000000', 'Black'), ('#808080', 'Grey'), ('#00FFFF', 'Cyan'), ('#800000', 'Maroon'), ('#008000', 'Dark Green'), ('#000080', 'Navy')], default='#00FF00', max_length=20),
        ),
    ]
