# Generated by Django 4.2.9 on 2024-01-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0052_projectdeliverables_deliverableenddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdeliverables',
            name='deliverableEndDate',
        ),
        migrations.RemoveField(
            model_name='projectdeliverables',
            name='deliverableStartDate',
        ),
    ]
