# Generated by Django 4.2.9 on 2024-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0053_remove_projectdeliverables_deliverableenddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeliverables',
            name='deliverableEndDate',
            field=models.TextField(default='09-01-2024'),
        ),
        migrations.AddField(
            model_name='projectdeliverables',
            name='deliverableStartDate',
            field=models.TextField(default='01-12-2024'),
        ),
    ]
