# Generated by Django 4.2.9 on 2024-01-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0054_projectdeliverables_deliverableenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeliverables',
            name='deliverableName',
            field=models.TextField(unique=True),
        ),
    ]
