# Generated by Django 4.2.9 on 2024-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0056_alter_projectdeliverables_deliverablename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeliverables',
            name='deliverableStatusColor',
            field=models.CharField(choices=[('green', 'Green'), ('#ecb753', 'Yellow'), ('red', 'Red')], default='green', max_length=20),
        ),
    ]
